version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/ghofig
    binary: ghofig
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: ghofig
    repository:
      owner: intaek-h
      name: homebrew-ghofig
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    homepage: "https://github.com/intaek-h/ghofig"
    description: "A TUI-based CLI tool for browsing and managing Ghostty terminal configuration"
    license: "MIT"
    test: |
      system "#{bin}/ghofig", "--version"
