Output assets/demo.gif

Set FontSize 16
Set Width 900
Set Height 600
Set Framerate 60
Set Theme "AtomOneLight"

Sleep 500ms
Type@200ms "ghofig"
Sleep 200ms
Enter
Sleep 2s

Enter
Sleep 1s

Type@200ms "font"
Sleep 1s

Down 1
Sleep 300ms
Down 1
Sleep 300ms
Down 1
Sleep 300ms
Down 1
Sleep 300ms
Down 1
Sleep 300ms
Down 1
Sleep 300ms
Down 1
Sleep 300ms
Down 1
Sleep 1s

Enter
Sleep 2s

Enter
Sleep 1s

Backspace 2
Sleep 1s

Type@200ms "20"
Sleep 1s
Enter
Sleep 3s

